import React, {StrictMode} from "react";
import ReactDOM from "react-dom/client";
import {RouterProvider, createRouter} from "@tanstack/react-router"

// This imports the route tree generated from the routes directory.
// The route tree is a nested object that represents the routes in the app, 
// It provides end to end type safety for the routes in the app.
// It is auto generated by the tanstack/react-router plugin for vite therefore will update with every new route
import {routeTree} from "./routeTree.gen"

import "./index.css";

const router=createRouter({routeTree})

// type gymanstics to achieve type safety for the router.
// 'makes zero sense', I know.
declare module "@tanstack/react-router" {
  interface Register{
    router: typeof router
  }
}


const rootElement=document.getElementById("root")
if (!rootElement?.innerHTML){
  const root=ReactDOM.createRoot(rootElement!)
  root.render(
    <StrictMode>
      <RouterProvider router={router}/>
    </StrictMode>
  )
}
