/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const LessonsPhysicsLazyImport = createFileRoute('/lessons/physics')()
const LessonsMathLazyImport = createFileRoute('/lessons/math')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LessonsPhysicsLazyRoute = LessonsPhysicsLazyImport.update({
  path: '/lessons/physics',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/lessons/physics.lazy').then((d) => d.Route),
)

const LessonsMathLazyRoute = LessonsMathLazyImport.update({
  path: '/lessons/math',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/lessons/math.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/lessons/math': {
      id: '/lessons/math'
      path: '/lessons/math'
      fullPath: '/lessons/math'
      preLoaderRoute: typeof LessonsMathLazyImport
      parentRoute: typeof rootRoute
    }
    '/lessons/physics': {
      id: '/lessons/physics'
      path: '/lessons/physics'
      fullPath: '/lessons/physics'
      preLoaderRoute: typeof LessonsPhysicsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  LessonsMathLazyRoute,
  LessonsPhysicsLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/lessons/math",
        "/lessons/physics"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/lessons/math": {
      "filePath": "lessons/math.lazy.tsx"
    },
    "/lessons/physics": {
      "filePath": "lessons/physics.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
